=== DiegoTorsani/TPSIT/Yaml/schema/rubrica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="rubrica">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="studente" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nome" type="xs:string"/>
              <xs:element name="votoPratico">
                <xs:simpleType>
                  <xs:restriction base="xs:decimal">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="10"/>
                    <xs:fractionDigits value="2"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="votoTeorico">
                <xs:simpleType>
                  <xs:restriction base="xs:decimal">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="10"/>
                    <xs:fractionDigits value="2"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="media">
                <xs:simpleType>
                  <xs:restriction base="xs:decimal">
                    <xs:minInclusive value="0"/>
                    <xs:maxInclusive value="10"/>
                    <xs:fractionDigits value="2"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="insufficiente">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="sÃ¬"/>
                    <xs:enumeration value="no"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="commento" type="xs:string" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== DiegoTorsani/TPSIT/xml/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<rubrica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../schema/rubrica.xsd">
  <studente>
    <nome>Matteo Matto</nome>
    <votoPratico>5</votoPratico>
    <votoTeorico>2.0</votoTeorico>
    <media>3.5</media>
    <insufficiente>sì</insufficiente>
    <commento>Coglione</commento>
  </studente>
  <studente>
    <nome>Luca Bianchi</nome>
    <votoPratico>4.0</votoPratico>
    <votoTeorico>5.0</votoTeorico>
    <media>4.5</media>
    <insufficiente>sì</insufficiente>
    <commento>Insufficiente: necessita recupero.</commento>
  </studente>
  <studente>
    <nome>Giulia Verdi</nome>
    <votoPratico>8.0</votoPratico>
    <votoTeorico>8.5</votoTeorico>
    <media>8.25</media>
    <insufficiente>no</insufficiente>
    <commento>Ottima prestazione complessiva.</commento>
  </studente>
</rubrica>
